Repository omnibenchmark/omnibenchmark, pull requests merged in 2025-07, with the labels that each got.

#144 Update installation docs in line with #143
  docs/src/howto.md
  docs/src/tutorial.md
Labels: documentation

#132 feat: enable --task-timeout
  .github/workflows/pipeline.yml
  .github/workflows/software_tests.yml
  .github/workflows/tests.yml
  README.md
  conda-test-environment.yml
  docs/mkdocs.yml
  docs/src/tutorial.md
  mac-test-environment.yml
  omnibenchmark/cli/run.py
  omnibenchmark/software/conda_backend.py
  omnibenchmark/software/easybuild_backend.py
  omnibenchmark/workflow/snakemake/rules/rule_node.smk
  omnibenchmark/workflow/snakemake/scripts/run_module.py
  omnibenchmark/workflow/snakemake/snakemake.py
  omnibenchmark/workflow/workflow.py
  scripts/create-micromamba-env.sh
  scripts/create-test-env.sh
  test-environment.yml
  tests/cli/test_run_benchmark_with_timeouts.py
Labels: enhancement, ready for review

#145 docs(design): add module contributor spec for discussion
  docs/design/000-template.md
  docs/design/001-module-metadata.md
  docs/design/README.md
Labels: enhancement
